import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
// import './globals.css'
import { Providers } from "./providers";
import Navbar from "./components/Header";
import Footer from './components/Footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Lentify',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <link
      rel="icon"
      href="/Logo.png"
      type="image/png"
      sizes="16x16"
    />
    <body className={inter.className}>
        <Providers>
            <Navbar/>
              {children}
            {/* <Footer/> */}
        </Providers>
      </body>
    </html>
  );
}
